### ISSUE TITLE
Assets init

### ISSUE THREAD

**Issue by lonnstyle** [lonnstyle/KPD#1]
- [x] minimap
- [x] map(sprite?tile?)
- [x] character(idle/walk animation)
- [ ] objectives(mission/minigames)
- [x] UI(you do not need to design the full UI, but icons needed)
- [x] logo/icon?

Please create a branch/make a fork on your own then send a merge request to `main`
assets should be stored in `Unity/Assets`(feel free to make sub-folders or rename exist sub-folders)
best to make a `README.md` for a reference on how you organize/use the assets
![](https://media.discordapp.net/attachments/895324526924161134/926667189325561856/IMG_0271.png)

**Comment by ArthurL0372** [comment]
![_index](https://user-images.githubusercontent.com/92207145/150099702-0f8f4ac6-a88e-4843-8689-862a2b8e6d3a.jpg)
![chat](https://user-images.githubusercontent.com/92207145/150099728-ca87ba14-1c1a-4983-8345-8cbef62d1412.png)
![delete](https://user-images.githubusercontent.com/92207145/150099732-5a7c9407-a680-4e57-949a-b0147a6b45e1.png)
![down](https://user-images.githubusercontent.com/92207145/150099736-86c7f02d-ac5c-4167-8e31-f0d376847253.png)
![facebook](https://user-images.githubusercontent.com/92207145/150099740-d4e796d3-f0d3-413a-a4f7-b84ac952c7cd.png)
![favourite](https://user-images.githubusercontent.com/92207145/150099742-d70e859e-81b0-4ede-aa3f-982d9a92a084.png)
![game](https://user-images.githubusercontent.com/92207145/150099744-f0a91893-1022-4426-ac60-abae41687f73.png)
![gift](https://user-images.githubusercontent.com/92207145/150099748-8058fdf0-cc99-46ae-9cc5-0018389182e1.png)
![help](https://user-images.githubusercontent.com/92207145/150099751-eb49a41e-9023-4724-8268-444f5e7e9647.png)
![home](https://user-images.githubusercontent.com/92207145/150099752-bee482dc-3f49-477a-b6ed-c3dc5a3de9e1.png)
![information](https://user-images.githubusercontent.com/92207145/150099755-ff8a1f74-c926-4621-b612-30d51fffbfa0.png)
![leave](https://user-images.githubusercontent.com/92207145/150099757-08df71e9-8959-4f7a-aff2-c09d2e65b350.png)
![left](https://user-images.githubusercontent.com/92207145/150099759-593506ce-6a87-4b10-991b-a67cf90b5c90.png)
![like](https://user-images.githubusercontent.com/92207145/150099760-09249160-98b6-425a-b54c-c3cf385fca55.png)
![lock](https://user-images.githubusercontent.com/92207145/150099762-d8e4253c-b596-4f87-91ad-ecd4c4268bfb.png)
![menu](https://user-images.githubusercontent.com/92207145/150099765-f6537e2f-d820-4881-9963-288c5486b7e3.png)
![minus](https://user-images.githubusercontent.com/92207145/150099766-22071f2c-5494-4785-81ae-4fb3054d1f96.png)
![money](https://user-images.githubusercontent.com/92207145/150099770-a8685c6b-7831-48dd-b609-95750f66585e.png)
![multiple](https://user-images.githubusercontent.com/92207145/150099774-aa1b510d-155a-47cb-a8d1-dc62a0e68ade.png)
![music](https://user-images.githubusercontent.com/92207145/150099778-051ee743-e49d-4058-940d-84c8b2715c55.png)
![next](https://user-images.githubusercontent.com/92207145/150099782-83249f3a-9f33-4415-bb27-6a8ef3ee6a1a.png)
![no](https://user-images.githubusercontent.com/92207145/150099784-d28384aa-7e57-4ff0-8936-6108b556e1f2.png)
![pause](https://user-images.githubusercontent.com/92207145/150099788-3b874438-7d2f-4cca-83c6-cfa308139371.png)
![play](https://user-images.githubusercontent.com/92207145/150099791-37d5d107-2975-4e8f-9f0c-39957c86a4ce.png)
![plus](https://user-images.githubusercontent.com/92207145/150099797-3e3ee923-2f17-45f6-805f-d6212abc2c0d.png)
![previous](https://user-images.githubusercontent.com/92207145/150099799-64bf2fbc-8e3f-4af7-ae3b-080365f15c81.png)
![prize](https://user-images.githubusercontent.com/92207145/150099801-efb2ac30-bc13-49d3-8998-2a8b0444ec0c.png)
![rank](https://user-images.githubusercontent.com/92207145/150099803-29e45baf-c055-4e05-a888-e10e9042d24f.png)
![reverse](https://user-images.githubusercontent.com/92207145/150099805-77f52419-585a-4b15-9665-5bb2086d7066.png)
![right](https://user-images.githubusercontent.com/92207145/150099809-9365db5b-935d-46b3-9b7d-c1001998b92b.png)
![save](https://user-images.githubusercontent.com/92207145/150099814-9dea8f09-cfe8-4e1e-aec2-eb41dbe22f56.png)
![search](https://user-images.githubusercontent.com/92207145/150099815-67be37ba-0a1b-41ca-bd3f-8b4b90c72967.png)
![setting](https://user-images.githubusercontent.com/92207145/150099819-6491234f-d8a3-45ad-a814-5a2480d10f92.png)
![shop](https://user-images.githubusercontent.com/92207145/150099821-866b8423-0cd0-4237-9f08-f83b7392dc90.png)
![single](https://user-images.githubusercontent.com/92207145/150099822-d283c531-5edd-4582-9606-b06a61b58942.png)
![sound](https://user-images.githubusercontent.com/92207145/150099823-3d152ad4-5309-47bc-a6e9-4bbf68b4a459.png)
![switch](https://user-images.githubusercontent.com/92207145/150099825-c3365d24-3a6a-4a15-81f9-f2c91f830d95.png)
![trophy](https://user-images.githubusercontent.com/92207145/150099827-ebd1dc53-6758-4813-8c45-40a08abd2253.png)
![twitter](https://user-images.githubusercontent.com/92207145/150099828-b46a2b50-b4e3-45ec-975a-dbb7cf0c33f5.png)
![up](https://user-images.githubusercontent.com/92207145/150099830-5021194a-b30d-4ac4-a6f5-d5bbb39ae4a3.png)
![yes](https://user-images.githubusercontent.com/92207145/150099832-910919db-ae32-411e-90a7-db16bdae824e.png)

**Comment by lonnstyle** [comment]
@ArthurL0372 for `walk`, can you find for a set of animation that won't change facing?
as it looks weird for now
and best if you can find an idle animation for player character
