### ISSUE TITLE
username TextField that follow player

### ISSUE THREAD

**Issue by lonnstyle** [lonnstyle/KPD#21]
- [ ] make a username TextField that follow player

_Originally posted by @lonnstyle in https://github.com/lonnstyle/KPD/issues/5#issuecomment-1032592334_

**Comment by tsuikit159** [comment]
https://www.youtube.com/watch?v=96HcOeO8EII&list=PLbrNQtHGAmEnSptE6uGTsXR2_TF5N6wwB&index=10&ab_channel=RedefineGamedev 
this video may helps

**Comment by lonnstyle** [comment]
not looking at the camera
