### ISSUE TITLE
map init

### ISSUE THREAD

**Issue by lonnstyle** [lonnstyle/KPD#31]
There's already an asset of the map background.
You should build map boundaries based on that, and make sure it works well with player collision
You may also try to make interactions (among players / with objectives), if you can't finish that, new an issue.
Do all the changes on a new branch, based on `dev`.
When you do rebase, first rebase `dev` on `main`, then rebase your branch on `dev`.
The command as follow:
```
git switch <target branch>
git rebase <base branch>
git push -f
```
As you rebased the branch, it is no longer a linear branch, which you need to force update, otherwise, you shouldn't force push

**Comment by tsuikit159** [comment]
https://www.youtube.com/watch?v=Hq_Gzia-Tbw&ab_channel=RedefineGamedev 
20:14 for tutorial

**Comment by lonnstyle** [comment]
awaiting objectives
