### ISSUE TITLE
UI placeholders

### ISSUE THREAD

**Issue by lonnstyle** [lonnstyle/KPD#7]
#5 #6 

- [x] Start menu
- [x] Settings menu
- [x] Host menu
- [x] minimap?
- [ ] chat?
- [ ] anything can think of

**Comment by Loui14lm** [comment]
https://www.figma.com/file/klPpFvO44G3mQHi9N0SEiG/Host-menu

**Comment by lonnstyle** [comment]
@Loui14lm do you have any idea on the background? looks too simple
also, may be align of the sliding bars would be better?
seems the chat icon is not aligned too, not sure if you pretended to make it deviate to the right or not

**Comment by Loui14lm** [comment]
> 

可以用個有星的太空做background，至於D位我再調整下

**Comment by Loui14lm** [comment]
![Host menuNew](https://user-images.githubusercontent.com/92239964/159638493-e08bf76d-d29b-4e5e-9e41-57546d117685.png)
